spring.application.name=backend

<<<<<<< HEAD
# DATABASE
=======
spring.datasource.url=${AMAZON_RDS_URL}
spring.datasource.username=${AMAZON_RDS_USERNAME}
spring.datasource.password=${AMAZON_RDS_PASSWORD}
>>>>>>> upstream/dev


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=${AMAZON_RDS_URL}
spring.datasource.username=${AMAZON_RDS_USERNAME}
spring.datasource.password=${AMAZON_RDS_PASSWORD}


